# suppress inspection "UnusedProperty" for whole file

# App
quarkus.banner.enabled=false
quarkus.console.color=true

# Image
quarkus.container-image.name=dashbude-operator
quarkus.container-image.build=true
quarkus.container-image.builder=docker
quarkus.docker.dockerfile-jvm-path=Dockerfile

# CRDs
quarkus.operator-sdk.crd.apply=true
quarkus.operator-sdk.crd.validate=false
quarkus.operator-sdk.crd.generate=true

# Operator
# quarkus.operator-sdk.bundle.channels=fast
# quarkus.operator-sdk.namespaces=JOSDK_WATCH_CURRENT
# quarkus.operator-sdk.generate-with-watched-namespaces=JOSDK_WATCH_CURRENT

